export const GET_USER = "GET_USER";
export const SET_USER = "SET_USER";
export const FETCH_WHISHLIST_BEGIN = "FETCH_WISHLIST_BEGIN";
export const FETCH_WHISHLIST_SUCCESS = "GET_WHISHLIST_SUCCESS";
export const ADD_WHISHLIST = "ADD_WHISHLIST";
export const REMOVE_WISHLIST = "REMOVE_WISHLIST";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const REMOVE_ADDRESS = "ADD_ADDRESS";

export const SET_BEAUTY_ROW = "SET_BEAUTY_ROW";
export const SET_POPULAR_ROW = "SET_POPULAR_ROW";
export const SET_DAILY_DISCOVER_ROW = "SET_DAILY_DISCOVER_ROW";
export const SET_CATEGORY_ROW = "SET_CATEGORY_ROW";
export const SET_PRODUCT = "SET_PRODUCT";
export const SET_ELECTRONIC_ROW = "SET_ELECTRONIC ROW";
export const SET_KIDS_ROW = "SET_KIDS_ROW";
export const SET_PET_PRODUCT_ROW = "SET_PET_PRODUCT_ROW";
export const SET_FLASHDEALS = "SET_FLASHDEALS";

export const SET_TRENDING_STORE = "SET_TRENDING_STORE";

export const FETCH_CATEGORIES_BEGIN = "FETCH_CATEGORIES_BEGIN";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";

export const FETCH_CATEGORY_PRODUCTS_BEGIN = "FETCH_CATEGORY_PRODUCTS_BEGIN";
export const FETCH_CATEGORY_PRODUCTS_SUCCESS =
  "FETCH_CATEGORY_PRODUCTS_SUCCESS";
export const ADD_CATEGORY_PRODUCTS = "ADD_CATEGORY_PRODUCTS";
export const REFRESH_CATEGORY_PRODUCTS_BEGIN =
  "REFRESH_CATEGORY_PRODUCTS_BEGIN";
export const REFRESH_CATEGORY_PRODUCTS_SUCCESS =
  "REFRESH_CATEGORY_PRODUCTS_SUCCESS";

export const SET_ACCOUNT_DETAILS = "SET_ACCOUNT_DETAILS";
export const FETCH_ACCOUNT_DETAILS_BEGIN = "FETCH_ACCOUNT_DETAILS_BEGIN";
export const FETCH_ACCOUNT_DETAILS_SUCCESS = "FETCH_ACCOUNT_DETAILS_SUCCESS";
export const UPDATE_ACCOUNT_DETAIL_BEGIN = "UPDATE_ACCOUNT_DETAIL_BEGIN";
export const CHANGE_PASSWORD_BEGIN = "CHANGE_PASSWORD_BEGIN";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const UPDATE_SHIPPING_ADDRESS_BEGIN = "UPDATE_SHIPPING_ADDRESS_BEGIN";
export const UPDATE_BILLING_ADDRESS_BEGIN = "UPDATE_BILLING_ADDRESS_BEGIN";
export const UPDATE_TOMATO_COINS = "UPDATE_TOMATO_COINS";
export const UPDATE_TOMATO_POINTS = "UPDATE_TOMATO_POINTS";

export const SAVE_HISTORY = "SAVE_HISTORY";

export const LOADING_CART = "LOADING_CART";
export const GET_ALL_CART = "GET_ALL_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART = "UPDATE_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SET_CART_ERROR = "SET_CART_ERROR";
export const CLEAR_CART = "CLEAR_CART";

export const ORDERS_FETCH_BEGIN = "ORDERS_FETCH_BEGIN";
export const ORDERS_FETCH_SUCCESS = "ORDERS_FETCH_SUCCESS";
export const CLEAR_ORDERS = "CLEAR_ORDERS";

export const FETCH_LIVE_VIDEOS_BEGIN = "FETCH_LIVE_VIDEOS_BEGIN";
export const UPDATE_LIVE_VIDEOS = "UPDATE_LIVE_VIDEOS";
export const IS_LIVE_VIDEOS = "IS_LIVE_VIDEOS";
export const UPDATE_IS_LIVE = "UPDATE_IS_LIVE";

export const TOMATO_SUPERFAST = "TOMATO_SUPERFAST";
export const TOMATO_THADINGYUT_GIFT_BASKETS = "TOMATO_THADINGYUT_GIFT_BASKETS";
export const TOMATO_MART_PROMOTIONS = "TOMATO_MART_PROMOTIONS";

//12.12
export const ADD_PROMO_PRODUCT = "ADD_PROMO_PRODUCT";
export const REMOVE_PROMO_PRODUCT = "REMOVE_PROMO_PRODUCT";
export const REMOVE_ALL_PROMOPRO = "REMOVE_ALL_PROMOPRO";
